---

- name: Configure elx-netbilling service
  config_template:
    src: "elx_netbilling_agent.service.j2"
    dest: "/etc/systemd/system/elx_netbilling_agent.service"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: Restart netbilling service
  tags:
    - elx-netbilling

- name: Retrieve URL for latest repo release
  run_once: true
  uri:
    url: https://api.github.com/repos/elastx/{{ elx_netbilling_repo }}/releases/latest
    method: GET
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ elx_github_token_ro }}"
      X-GitHub-Api-Version: "2022-11-28"
  register: elx_netbilling_url
  tags:
    - elx-netbilling

- name: Download latest release
  uri:
    url: '{{ elx_netbilling_url.json.assets[0].url }}'
    method: GET
    dest: "{{ elx_netbilling_path }}"
    headers:
      Accept: "application/octet-stream"
      Authorization: "Bearer {{ elx_github_token_ro }}"
      X-GitHub-Api-Version: "2022-11-28"
  tags:
    - elx-netbilling
