---
# Copyright 2017, Elastx AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add opflex repository (APT)
  apt_repository:
    repo: "{{ opflex_repo.repo }}"
    state: "{{ opflex_repo.state }}"
  register: opflex_add_repo
  until: opflex_add_repo|success
  retries: 5
  delay: 2
  when:
    - ansible_pkg_mgr == 'apt'
  tags:
    - opflex-install
    - opflex-distro-packages

- name: Install opflex distro packages
  package:
    name: "{{ neutron_opflex_package_list }}"
    state: "{{ neutron_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr in ['apt', 'zypper']) | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  tags:
    - opflex-install
    - opflex-distro-packages

- name: Add neutron user to _lldpd group
  user:
    name: "{{ neutron_system_user_name }}"
    groups: _lldpd
    append: yes
  when:
    - neutron_services['opflex-neutron-agent']['group'] in group_names
  tags:
    - opflex-install
    - opflex-distro-packages

- name: Install opflex pip packages
  pip:
    name: "{{ neutron_optional_opflex_pip_packages | join(' ') }}"
    state: latest
    virtualenv: "{{ neutron_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ neutron_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  notify: Restart neutron services
  tags:
    - opflex-install
    - opflex-pip-packages

- name: Install opflex gbp and unified pip packages
  pip:
    name: "{{ neutron_optional_opflex_unified_pip_packages | join(' ') }}"
    state: latest
    virtualenv: "{{ neutron_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ neutron_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  notify: Restart neutron services
  when:
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-install
    - opflex-unified-pip-packages

- name: Install opflex agent pip packages
  pip:
    name: "{{ neutron_optional_opflex_agent_pip_packages | join(' ') }}"
    state: latest
    virtualenv: "{{ neutron_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ neutron_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  notify: Restart neutron services
  when:
    - neutron_services['opflex-neutron-agent']['group'] in group_names
  tags:
    - opflex-install
    - opflex-agent-pip-packages

- name: Copy dhclient config
  template:
    src: "dhclient.conf.j2"
    dest: "{{ opflex_dhclient_conf_target }}"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - opflex-config

- name: Cycle apic interface
  shell: |
    ifdown {{ opflex_uplink_iface }} && ifup {{ opflex_uplink_iface }}
  tags:
    - opflex-config

- name: Copy apic plugin config
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "0640"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "plugins/ml2/ml2_conf_cisco_apic.ini.j2"
      dest: "{{ neutron_conf_dir }}/plugins/ml2/ml2_conf_cisco_apic.ini"
      config_overrides: "{{ neutron_opflex_ml2_conf_ini_overrides }}"
      config_type: "ini"
    - src: "plugins/ml2/cisco_apic_network_constraints.ini.j2"
      dest: "{{ neutron_conf_dir }}/plugins/ml2/cisco_apic_network_constraints.ini"
      config_overrides: "{{ neutron_opflex_network_constraints_ini_overrides }}"
      config_type: "ini"
  when:
    - (neutron_services['neutron-server']['group'] in group_names) or (neutron_services['opflex-apic-agent']['group'] in group_names)
  tags:
    - opflex-config

- name: Perform gbp db upgrade
  command: "{{ neutron_bin }}/gbp-db-manage --config-file {{ neutron_db_config }} upgrade head"
  become: yes
  become_user: "{{ neutron_system_user_name }}"
  when:
    - "ansible_local['openstack_ansible']['neutron']['need_gbp_init'] | bool"
    - "inventory_hostname == groups[neutron_services['neutron-server']['group']][0]"
    - (neutron_services['neutron-server']['group'] in group_names) and ((opflex_plugin_mode == 'unified') or (opflex_plugin_mode == 'gbp'))
  tags:
    - opflex-gbp-init

- name: Disable the gbp init fact
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: neutron
    option: "need_gbp_init"
    value: "False"
  when:
    - (neutron_services['neutron-server']['group'] in group_names) and ((opflex_plugin_mode == 'unified') or (opflex_plugin_mode == 'gbp'))
  tags:
    - opflex-gbp-init

- name: Refresh local facts
  setup:
    filter: ansible_local
    gather_subset: "!all"
  when:
    - (neutron_services['neutron-server']['group'] in group_names) and ((opflex_plugin_mode == 'unified') or (opflex_plugin_mode == 'gbp'))
  tags:
    - opflex-gbp-init

- name: Ensure aim config directory and log files exists
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner|default(neutron_system_user_name) }}"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "{{ item.mode }}"
  with_items:
    - path: /etc/aim
      state: directory
      owner: root
      mode: "0755"
    - path: /run/aid/events
      state: directory
      mode: "0755"
    - path: /var/log/aim-aid.log
      state: touch
      mode: "0640"
    - path: /var/log/aim-event-service-polling.log
      state: touch
      mode: "0640"
    - path: /var/log/aim-event-service-rpc.log
      state: touch
      mode: "0640"
  when:
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-aim-config

- name: Copy aim service config
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "0640"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "aim.conf.j2"
      dest: "/etc/aim/aim.conf"
      config_overrides: "{{ neutron_opflex_aim_conf_ini_overrides }}"
      config_type: "ini"
    - src: "aimctl.conf.j2"
      dest: "/etc/aim/aimctl.conf"
      config_overrides: "{{ neutron_opflex_aimctl_conf_ini_overrides }}"
      config_type: "ini"
  when:
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-aim-config

- name: Perform aim db upgrade
  command: "{{ neutron_bin }}/aimctl db-migration upgrade head"
  become: yes
  become_user: "{{ neutron_system_user_name }}"
  when:
    - "ansible_local['openstack_ansible']['neutron']['need_aim_init'] | bool"
    - "inventory_hostname == groups[neutron_services['neutron-server']['group']][0]"
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-aim-init

- name: Perform aim config update
  command: "{{ neutron_bin }}/aimctl config update"
  become: yes
  become_user: "{{ neutron_system_user_name }}"
  when:
    - "ansible_local['openstack_ansible']['neutron']['need_aim_init'] | bool"
    - "inventory_hostname == groups[neutron_services['neutron-server']['group']][0]"
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-aim-init

- name: Disable the aim init fact
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: neutron
    option: "need_aim_init"
    value: "False"
  when:
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-aim-init

- name: Refresh local facts
  setup:
    filter: ansible_local
    gather_subset: "!all"
  when:
    - (neutron_services['opflex-aim-aid']['group'] in group_names) and (opflex_plugin_mode == 'unified')
  tags:
    - opflex-aim-init

- name: Copy opflex ovs agent config
  config_template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "0640"
    config_overrides: "{{ item.config_overrides }}"
    config_type: "{{ item.config_type }}"
  with_items:
    - src: "opflex-agent-ovs.conf.j2"
      dest: "/etc/opflex-agent-ovs/opflex-agent-ovs.conf"
      config_overrides: "{{ neutron_opflex_ovs_agent_json_overrides }}"
      config_type: "json"
  when:
    - neutron_services['opflex-ovs-agent']['group'] in group_names
  tags:
    - opflex-config

- name: Create OVS integration bridge
  openvswitch_bridge:
    bridge: "{{ opflex_integration_bridge }}"
    state: present
    fail_mode: secure
  when:
    - neutron_services['opflex-ovs-agent']['group'] in group_names
  tags:
    - opflex-config

- name: Create OVS port (VXLAN)
  openvswitch_port:
    bridge: "{{ opflex_integration_bridge }}"
    port: "{{ opflex_integration_bridge }}_vxlan0"
    state: present 
    set: "Interface {{ opflex_integration_bridge }}_vxlan0 type=vxlan options:remote_ip=flow options:dst_port=8472"
  when:
    - (neutron_services['opflex-ovs-agent']['group'] in group_names) and (neutron_vxlan_enabled | bool)
  tags:
    - opflex-config

- name: Create OVS port (VLAN)
  openvswitch_port:
    bridge: "{{ opflex_integration_bridge }}"
    port: "{{ opflex_vlan_trunk_iface }}"
    state: present 
  when:
    - (neutron_services['opflex-ovs-agent']['group'] in group_names) and (not neutron_vxlan_enabled | bool)
  tags:
    - opflex-config
