---
- name: Stop old agent-ovs service
  service:
    name: "agent-ovs"
    state: stopped
    enabled: no
  when: "neutron_services['opflex-ovs-agent']['group'] in group_names"

# No need to uninstall, package have alias to old package name
#- name: Uninstall old agent-ovs package
#  package:
#    name: agent-ovs
#    state: absent
#  when: "neutron_services['opflex-ovs-agent']['group'] in group_names"
